//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoNorBeadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int score_id { get; set; }
        public string score1 { get; set; }
        public int score_test_id { get; set; }
        public long score_student_om_id { get; set; }
    }
}
