//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoNorBeadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long student_om_id { get; set; }
        public long student_id { get; set; }
        public string student_first_name { get; set; }
        public string student_last_name { get; set; }
        public System.DateTime student_birth_date { get; set; }
        public string student_gender { get; set; }
        public string student_city { get; set; }
        public int student_zip { get; set; }
        public string student_home_address { get; set; }
        public string student_email { get; set; }
        public string student_home_phone { get; set; }
        public string student_mobile { get; set; }
        public int student_class_id { get; set; }
        public int student_user_id { get; set; }
    }
}
