
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KoNorBeadando
{

using System;
    using System.Collections.Generic;
    
public partial class Teacher
{

    public long teacher_om_id { get; set; }

    public string teacher_first_name { get; set; }

    public string teacher_last_name { get; set; }

    public System.DateTime teacher_birth_date { get; set; }

    public string teacher_gender { get; set; }

    public string teacher_city { get; set; }

    public int teacher_zip { get; set; }

    public string teacher_home_address { get; set; }

    public string teacher_email { get; set; }

    public string teacher_home_phone { get; set; }

    public string teacher_mobile { get; set; }

    public Nullable<int> teacher_class_id { get; set; }

    public int teacher_lesson_id { get; set; }

    public int teacher_user_id { get; set; }

}

}
