
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KoNorBeadando
{

using System;
    using System.Collections.Generic;
    
public partial class User
{
        public User(User user)
        {
            user_id = user.user_id;
            username = user.username;
            password = user.password;
            user_access_rank = user.user_access_rank;
        }
        public User()
        {

        }

        public int user_id { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public int user_access_rank { get; set; }

}

}
